# Site Info
title: Kazi Ridwan
tagline: "Kazi's blog"
description: 'A Jekyll theme adapted from <a href="http://lanyon.getpoole.com/" target="_blank">Lanyon</a>. Made by <a href="http://codinfox.github.io" target="_blank">@codinfox</a>.'
baseurl: "/blog.2016"
url: http://kaziridwan.github.io/blog.2016
logo: '/public/logo.png'

# Site configurations
gems:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss    
paginate: 5
paginate_path: '/blog.2016/page:num'
permalink: pretty

version: 1.0.0

# About/contact
author:
  name: Kazi Ridwan
  description: <strong>Dreamer</strong>, in a love affair with all things code.
  gravatar: 851f42bf5235d95574508d5ab93ccca7 # md5 hash of your email address
  contact:
    linkedin:  https://www.linkedin.com/in/kazi-ridwan
    github:    https://github.com/kaziridwan
    # facebook:  <hide>
    twitter:   https://twitter.com/ridwanshere
    # weibo:     <hide>
    email:     mailto:ridwan.arefin@gmail.com

# Navigation (2nd level links supported)
nav:
  Home:           
    - '/'
  Blog:           
    - '/blog/'
    - { Categories: '/blog.2016/categories/' }
    - { Tags: '/blog.2016/tags/' }
  About:          
    - '/about/'
  Github Project: 
    - 'http://github.com/kaziridwan'

# Where are tags and categories displayed
tag_page: '/blog.2016/tags/'
category_page: '/blog.2016/categories/'

hero:
  image: /public/img/we_will_be_giants_by_yalestewart.jpg
  caption: Original Artwork &copy; <a href="http://yalestewart.deviantart.com/art/We-Will-Be-Giants-370176475">Yale Stewart</a>

# Puglins
mathjax: true # whether support mathjax
google_analytics_token: 'UA-67799784-2' # leave blank if you don't want google analytics
disqus_short_name: 'ridwanshere' # leave blank if you don't want disqus
